app:
	echo "use make run instead"

tools:
	cd $(EXPRESSPATH) && npm install --save nodemon
	cd $(EXPRESSPATH) && npm install --save mocha
	cd $(EXPRESSPATH) && npm install --save should
	cd $(EXPRESSPATH) && npm install --save supertest

deps:
	npm install

run:
	cd $(EXPRESSPATH) && npm run run

fmt:
	echo "not implemented"

test:
	cd $(EXPRESSPATH) && npm run test

lint:
	echo "not implemented"

coverage:
	echo "not implemented"
