version: "3"
services:
  project-name:
    image: project-name_project-name
    networks:
      default:
      swarm_routing:
        aliases:
          - project-name.localtest.me
    env_file: .env
    environment:
      APACHE_RUN_USER: $APACHE_RUN_USER
      MYSQL_HOST: project-name-mariadb
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 16M
        limits:
          memory: 16M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
    volumes:
      - ./microservice:/var/www/html

  project-name-mariadb:
    image: mariadb
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 10
    volumes:
      - project-name:/var/lib/mysql
volumes:
  project-name-mariadb:
networks:
  default:
    internal: true
    driver: overlay
  swarm_routing:
    external: true